### ISSUE TITLE
Not working on Blender 2.76

### ISSUE THREAD

**Issue by wallabra** [seece/SpriteBatchRender#1]
For some reason it don't work in my Blender, please fix, thanks!

**Comment by pekkavaa** [comment]
Thanks for the report. Did the addon install correctly? Can you see the
section it adds to the rendering pane?
1.12.2015 22.48 "Gustavo6046" notifications@github.com kirjoitti:

**Comment by wallabra** [comment]
The addon installs correctly, but I can't see the section it adds to the rendering tab.
I just put the addon file in Blender's Plugins folder.

**Comment by pekkavaa** [comment]
I just tried this myself with 2.76b and it works fine. Maybe you forgot to enable the plugin? The checkbox is pretty easy to miss. :) 

I updated the installation instructions to be easier: https://github.com/seece/SpriteBatchRender#installation

**Comment by wallabra** [comment]
I did enabled it, but I didn't install from file, I just copied it and pasted to the Plugins folder, But where is it located when the button is working?

**Comment by pekkavaa** [comment]
Great to hear it works!

**Comment by wallabra** [comment]
I still can't find the button. Maybe the mod is working for me but I simply don't know where it is. Could you please, kindly point me out to its location? :)

**Comment by pekkavaa** [comment]
After the add-on has been installed and enabled (see the marked checkbox in the picture) the new section should be visible under the Render pane. 

Please see this screenshot: http://i.imgur.com/eTUqZQi.png

**Comment by wallabra** [comment]
Oh wait, I actually am using Blender 2.75a and I forgot it! Sorry for this confusion :P But anyway.
Also I found it :DDDDD Thank you SO much! Now I don't need to hand draw my sprites pixel by pixel in Grafx2 as I usually do xD
And one more thing: it raises "not enough frames in custom framenames" error when I try to use it. :/

**Comment by pekkavaa** [comment]
Alright cool! Try to set the Blender animation frame start to 1 and end to 1 so you aren't rendering the default 250 frames. Also make sure the **Frame names** option is set to `ABCDEFGHIJKLMN` and **Step names** to `12345678`.

**Comment by wallabra** [comment]
Thanks! Now it renders 3 images of the target, left, middle and right of camera view respectively... And I don't understand why! Maybe I should make the camera view 128x128 but I don't know how... :/

**Comment by pekkavaa** [comment]
Please try the example .blend file mentioned in the readme and see if that works. You need to have the  camera tracking set up properly.

**Comment by wallabra** [comment]
I'll try that example, I hope it works :) Also do you want to check out [MyAntSim](https://github.com/Gustavo6046/MyAntSim)?
