### ISSUE TITLE
Angle seems to be in reverse order

### ISSUE THREAD

**Issue by nashmuhandes** [seece/SpriteBatchRender#4]
For example, A3 for the Doom player looks like the player is facing to the LEFT <-- this way

However, A3 for this script makes my character look to the RIGHT --> this way

**Comment by pekkavaa** [comment]
Hmm interesting, I've used this successfully with ZDoom but maybe I've broken something with a recent change.

**Comment by pekkavaa** [comment]
Fixed in 5f0335bd6e0136e5324033e81aa4b3b137104f53
