### ISSUE TITLE
Update for Blender 2.8

### ISSUE THREAD

**Issue by HeadClot** [seece/SpriteBatchRender#5]
Hey would it be possible to update this script to support blender 2.8?

**Comment by pekkavaa** [comment]
A good idea. I'll try to look into it but no promises when!

**Comment by HeadClot** [comment]
Thank you :)

**Comment by pekkavaa** [comment]
I upgraded the plugin and also added a CTRL+C quitting feature. The code lives in its own branch right now: https://github.com/seece/SpriteBatchRender/tree/feature-migrate-280

I will merge it into master once the Blender 2.80 goes out of beta.

**Comment by HeadClot** [comment]
Thank you so much :)
