### ISSUE TITLE
Traceback error at Render Batch with Blender 2.81a

### ISSUE THREAD

**Issue by EliasMasche** [seece/SpriteBatchRender#7]
I am trying to use the addon with the latest version of Blender 2.81a where i have this 2 errors when trying to render

> Traceback (most recent call last):
  File "C:\Users\EliasM\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\sprite_batch_render.py", line 128, in execute
    frame_end
  File "C:\Users\EliasM\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\sprite_batch_render.py", line 174, in render
    scene.update()
AttributeError: 'Scene' object has no attribute 'update'
location: <unknown location>:-1

![Screenshot (16)](https://user-images.githubusercontent.com/6045426/72953238-3c466080-3d73-11ea-97e8-a028e47ca828.png)

Using the example suzanne2.blend is enough to get the error

**Comment by pekkavaa** [comment]
Thank you so much for taking the time to report this! It's been fixed now in https://github.com/seece/SpriteBatchRender/commit/7a2dab1e4bfbd570c6448c0d84626533a6776bf0 so please try installing the new version.
